In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
df = pd.read_csv('gurgaon_properties.csv')

In [ ]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
163,3 BHK Flat in Sector 81 Gurgaon,flat,DLF The Ultima4.0 ★,2.40,11412.0,2103.0,Super Built up area 2103(195.38 sq.m.),3,4,3+,servant room,"192, Sector 81 Gurgaon, Gurgaon, Haryana",19.0,North-West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",Located in the popular residential address of ...,"['1 Fridge', '1 Fan', '1 Exhaust Fan', '1 Dini...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
2980,4 BHK Flat in Sector 69 Gurgaon,flat,Tulip Violet4.2 ★,1.90,9452.0,2010.0,Super Built up area 2010(186.74 sq.m.),4,4,2,not available,"Sector 69 Gurgaon, Gurgaon, Haryana",0.0,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This lovely 4 bhk apartment/flat with extended...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
1872,3 BHK Flat in Sector 109 Gurgaon,flat,ATS Tourmaline3.9 ★,1.40,8000.0,1750.0,Super Built up area 1750(162.58 sq.m.)Built Up...,3,3,3+,store room,"8th Floor, Sector 109 Gurgaon, Gurgaon, Haryana",8.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",Ats tourmaline is one of the most popular dest...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
40,2 BHK Flat in Samaspur,flat,Samaspurkunj,0.55,5238.0,1050.0,Carpet area: 1050 (97.55 sq.m.),2,2,0,not available,"503, 5th Floor, Samaspur, Gurgaon, Haryana",5.0,NaN,1 to 5 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...","This property is adjacent sector -51, actual p...","['2 Bed', '3 Wardrobe', '3 Fan', '1 Sofa', '2 ...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2143,4 BHK Flat in Sector 85 Gurgaon,flat,SS The Leaf3.8 ★,2.10,7467.0,2812.0,Super Built up area 2812(261.24 sq.m.)Built Up...,4,4,3,"pooja room,study room,servant room","Sector 85 Gurgaon, Gurgaon, Haryana",7.0,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",Ss is one of the most popular destination for ...,"['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou..."

In [ ]:
df.shape

(3961, 20)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [ ]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [ ]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,8 Bedroom House for sale in Sector 12A Gurgaon,house,independent,3.50,133079.0,263.0,Plot area 263(24.43 sq.m.)Built Up area: 4800 ...,8,8,3+,"pooja room,study room,servant room","313, Sector 12A Gurgaon, Gurgaon, Haryana",3.0,South-East,1 to 5 Year Old,"['Hanuman Mandir', 'Dental Health Centre', 'No...",It is situated in well established gated commu...,"['1 Water Purifier', '14 Fan', '1 Exhaust Fan'...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
1,2 BHK Flat in Sector-2 Sohna,flat,Supertech Hill Town,0.75,6250.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,"pooja room,study room,others","Hill View Residences, Sector-2 Sohna, Gurgaon,...",17.0,North,Aug 2024,"['Discount Department Store', 'Omaxe Gurgaon M...",Hill facing apartment in the best luxurious up...,"['5 Light', '3 AC', '1 Modular Kitchen', '2 Wa...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2,3 BHK Flat in Sector 106 Gurgaon,flat,Paras Dews,1.14,6000.0,1900.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3,4,3,"study room,servant room","Sector 106 Gurgaon, Gurgaon, Haryana",8.0,South,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Located in the popular residential address of ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
3,3 BHK Flat in Sector 53 Gurgaon,flat,Tulip Monsella,8.25,28000.0,2946.0,Super Built up area 2940(273.13 sq.m.),3,4,3,servant room,"Sector 53 Gurgaon, Gurgaon, Haryana",8.0,NaN,Nov 2025,"['Sector 53-54 Metro Station', 'Central Plaza ...",Top of the line property and last property on ...,"['1 Water Purifier', '1 Fridge', '1 Washing Ma...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,NaN,NaN,NaN,Plot area 350(292.64 sq.m.),5,5,3,not available,"Sector 66 Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This property situated in marbella sector 65 g...,"['5 Fan', '1 Exhaust Fan', '6 Geyser', '1 Micr...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Safety4 out of 5', ..."

In [ ]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [ ]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,8 Bedroom House for sale in Sector 12A Gurgaon,house,independent,Sector 12A,3.50,133079.0,263.0,Plot area 263(24.43 sq.m.)Built Up area: 4800 ...,8,8,3+,"pooja room,study room,servant room","313, Sector 12A Gurgaon, Gurgaon, Haryana",3.0,South-East,1 to 5 Year Old,"['Hanuman Mandir', 'Dental Health Centre', 'No...",It is situated in well established gated commu...,"['1 Water Purifier', '14 Fan', '1 Exhaust Fan'...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
1,2 BHK Flat in Sector-2 Sohna,flat,Supertech Hill Town,Sector-2 Sohna,0.75,6250.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,"pooja room,study room,others","Hill View Residences, Sector-2 Sohna, Gurgaon,...",17.0,North,Aug 2024,"['Discount Department Store', 'Omaxe Gurgaon M...",Hill facing apartment in the best luxurious up...,"['5 Light', '3 AC', '1 Modular Kitchen', '2 Wa...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2,3 BHK Flat in Sector 106 Gurgaon,flat,Paras Dews,Sector 106,1.14,6000.0,1900.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3,4,3,"study room,servant room","Sector 106 Gurgaon, Gurgaon, Haryana",8.0,South,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Located in the popular residential address of ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
3,3 BHK Flat in Sector 53 Gurgaon,flat,Tulip Monsella,Sector 53,8.25,28000.0,2946.0,Super Built up area 2940(273.13 sq.m.),3,4,3,servant room,"Sector 53 Gurgaon, Gurgaon, Haryana",8.0,NaN,Nov 2025,"['Sector 53-54 Metro Station', 'Central Plaza ...",Top of the line property and last property on ...,"['1 Water Purifier', '1 Fridge', '1 Washing Ma...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,Sector 66,NaN,NaN,NaN,Plot area 350(292.64 sq.m.),5,5,3,not available,"Sector 66 Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This property situated in marbella sector 65 g...,"['5 Fan', '1 Exhaust Fan', '6 Geyser', '1 Micr...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Safety4 out of 5', ..."

In [ ]:
df['sector'] = df['sector'].str.lower()

In [ ]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,8 Bedroom House for sale in Sector 12A Gurgaon,house,independent,sector 12a,3.50,133079.0,263.0,Plot area 263(24.43 sq.m.)Built Up area: 4800 ...,8,8,3+,"pooja room,study room,servant room","313, Sector 12A Gurgaon, Gurgaon, Haryana",3.0,South-East,1 to 5 Year Old,"['Hanuman Mandir', 'Dental Health Centre', 'No...",It is situated in well established gated commu...,"['1 Water Purifier', '14 Fan', '1 Exhaust Fan'...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
1,2 BHK Flat in Sector-2 Sohna,flat,Supertech Hill Town,sector-2 sohna,0.75,6250.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,"pooja room,study room,others","Hill View Residences, Sector-2 Sohna, Gurgaon,...",17.0,North,Aug 2024,"['Discount Department Store', 'Omaxe Gurgaon M...",Hill facing apartment in the best luxurious up...,"['5 Light', '3 AC', '1 Modular Kitchen', '2 Wa...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2,3 BHK Flat in Sector 106 Gurgaon,flat,Paras Dews,sector 106,1.14,6000.0,1900.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3,4,3,"study room,servant room","Sector 106 Gurgaon, Gurgaon, Haryana",8.0,South,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Located in the popular residential address of ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
3,3 BHK Flat in Sector 53 Gurgaon,flat,Tulip Monsella,sector 53,8.25,28000.0,2946.0,Super Built up area 2940(273.13 sq.m.),3,4,3,servant room,"Sector 53 Gurgaon, Gurgaon, Haryana",8.0,NaN,Nov 2025,"['Sector 53-54 Metro Station', 'Central Plaza ...",Top of the line property and last property on ...,"['1 Water Purifier', '1 Fridge', '1 Washing Ma...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,sector 66,NaN,NaN,NaN,Plot area 350(292.64 sq.m.),5,5,3,not available,"Sector 66 Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This property situated in marbella sector 65 g...,"['5 Fan', '1 Exhaust Fan', '6 Geyser', '1 Micr...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Safety4 out of 5', ..."

In [ ]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 65                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
nirvana country                                               53
sector 37c                                                    53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
sector 113                                                    43
dlf phase 2                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 54                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
dlf phase 3                                                   22
sector 67a                                                    22
sector 111                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 110                                                    16
sushant lok phase 3                                           16
sector 99                                                     16
sector 63                                                     15
sector 60                                                     15
sector 14                                                     15
sector 53                                                     14
gwal pahari                                                   14
sector 76                                                     14
dlf phase 5                                                   14
sector 1 imt manesar                                          14
sector 3                                                      14
sector 52                                                     14
rajendra park                                                 14
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 50                                                     12
uppals southend                                               12
sector 38                                                     12
sohna road                                                    12
sector 39                                                     12
sector 93                                                     12
sector 31                                                     12
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 4                                                       9
south city 1                                                   9
sector 55                                                      9
ashok vihar phase 2                                            9
sector 95a                                                     9
sector 89 a                                                    8
c block sushant lok phase 1                                    8
mehrauli  road                                                 8
dwarka expressway                                              8
sector 40                                                      8
sector 57                                                      8
sector 59                                                      8
malibu town                                                    8
sector 43                                                      8
sector 10a                                                     8
palam vihar extension                                          8
sector 36 sohna                                                7
surat nagar 1                                                  7
mianwali colony                                                7
sector 58                                                      7
sector 51                                                      7
sector 11                                                      7
sector 26                                                      7
new colony                                                     7
sector 1                                                       6
jacobpura                                                      6
rajiv nagar                                                    6
jyoti park                                                     6
ashok vihar                                                    6
sector 5                                                       6
sector 30                                                      5
new palam vihar                                                5
manesar                                                        5
saraswati vihar                                                5
arjun nagar                                                    5
sector 2                                                       5
sector 23a                                                     5
chakkarpur                                                     5
sector 28                                                      5
dayanand colony                                                5
sector 9                                                       5
ansal plaza                                                    5
subhash nagar                                                  5
sushant lok phase 2                                            5
sector 80                                                      5
sector 105                                                     5
greenwood city                                                 5
sector 12a                                                     4
bhondsi                                                        4
ravi nagar                                                     4
sector 36                                                      4
madanpuri                                                      4
sector 12                                                      4
surya vihar                                                    4
shivaji nagar                                                  4
sector 17                                                      4
garhi harsaru                                                  4
krishna colony                                                 4
bhim nagar                                                     4
baldev nagar                                                   4
valley view estate                                             4
adarsh nagar                                                   4
new                                                            4
shivpuri                                                       4
imt manesar                                                    4
sector 3a                                                      4
vishnu garden                                                  4
suncity                                                        4
sector 45                                                      4
devilal colony                                                 4
dharam colony                                                  4
sector 6                                                       4
a block sushant lok phase 1                                    3
sector 73                                                      3
mg road                                                        3
maruti kunj                                                    3
sector 17a                                                     3
sector 27                                                      3
sector 110 a                                                   3
sector 88b                                                     3
sector 8                                                       3
b block sushant lok phase 1                                    3
sector 23                                                      3
patel nagar                                                    3
gandhi nagar                                                   3
shakti nagar                                                   3
sector 17b                                                     3
prem nagar                                                     3
sector 15                                                      3
laxmi garden                                                   3
pratap nagar                                                   2
iffco chowk                                                    2
new basti                                                      2
bhawani enclave                                                2
sheetla colony                                                 2
daulatabad                                                     2
mayfield garden                                                2
golf course road                                               2
farukhnagar                                                    2
acharya puri                                                   2
, delhi ncr                                                    2
sushant lok                                                    2
sector 15 part 1                                               2
sector 41                                                      2
sector 21                                                      2
new palam vihar phase 2                                        2
sector 32                                                      2
shanti nagar                                                   2
ambience island                                                2
golf course ext road                                           2
sohna  road                                                    2
lajpat nagar                                                   2
sector-2 sohna                                                 2
nars                                                           2
surat nagar phase 2                                            2
mohan nagar                                                    2
manohar nagar                                                  2
bissar                                                         2
sector 24                                                      2
samaspur                                                       2
sector 15 part 2                                               2
faridabad road                                                 2
sispal vihar                                                   2
block a surya vihar                                            2
shankar vihar                                                  2
surat nagar                                                    2
rosewood                                                       2
hira nagar                                                     2
sector-11 sohna                                                2
west rajiv nagar                                               2
rajiv chowk                                                    2
new palam vihar phase 1                                        2
hsiidc plot sector 1 imt manesar                               1
lucknow                                                        1
sector 42                                                      1
block h ashok vihar phase iii extension                        1
saroop garden rajendra park                                    1
sector-7 hous                                                  1
naharpur rupa                                                  1
saraswati enclave                                              1
ats marigold                                                   1
old delhi road, opp sector-14                                  1
kanahi                                                         1
ashok vihar phase i                                            1
sector-5 sheetla colony                                        1
sector 4 urban estate                                          1
laxman vihar, railway road,                                    1
anand garden, sector-105                                       1
urban estate, sector 5                                         1
vir nagar                                                      1
mahalaxmi garden, rajendra place                               1
near khandsa road                                              1
sector 9b                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
ram nagar                                                      1
sector 37a                                                     1
new jyoti park                                                 1
hno 13 sagar enclave sura                                      1
alipur                                                         1
near euro                                                      1
godrej aria , sector 79 ,                                      1
block g sector-57                                              1
b1 block sector 57                                             1
garauli kalan                                                  1
sai kunj                                                       1
v block dlf phase 3                                            1
bhimgarh kheri phase 3                                         1
near nand hospital                                             1
south city                                                     1
bptp                                                           1
sector 5 chowk                                                 1
cyber city                                                     1
kheri                                                          1
dhankot                                                        1
begampur khatola                                               1
rajiv colony                                                   1
sector 21a faridabad                                           1
near pataudi chowk                                             1
gopal nagar, garhi ghasita, sonipat                            1
laxmna vihar, phase 2                                          1
jat colony,fazilpur/taj nagar road                             1
carterpuri village                                             1
ansal's palam vihar                                            1
sector 37b                                                     1
new colony, sector 7                                           1
civil l                                                        1
damdma                                                         1
near sector 1 market                                           1
jacobpura near sadar bazar                                     1
park view                                                      1
ashok vihar phase 3                                            1
huda saraswati vihar                                           1
part 3 sector 5                                                1
khandsa                                                        1
ravi nager basai road                                          1
sector-35 sohna                                                1
udyog vihar phase 1                                            1
devi lal colony gali no 12 gurgaon nr omkar public school      1
shivji park colony                                             1
nirvana country pocket h                                       1
om nagar                                                       1
sadar bazar                                                    1
bhora kalan                                                    1
sector 13                                                      1
tekchand nagar                                                 1
sector-5 sohna                                                 1
mahavir pura                                                   1
pataudi road                                                   1
sector 17c                                                     1
heritage city                                                  1
g block dlf city phase 1                                       1
sultanpur                                                      1
rattan garden                                                  1
Name: count, dtype: int64

In [ ]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [ ]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [ ]:
df['sector'].value_counts()

sector
sohna road road               175
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 90                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 37c                     53
sector 43                      53
sector 70                      53
sector 84                      51
sector-33 sohna road road      51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 57                      24
sector 112                     24
sector 24                      24
sector 105                     23
sector 14                      23
sector 88a                     23
sector 33                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 3                       20
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 62                      17
sector 91                      17
sector 99                      16
sector 110                     16
sector 63                      15
sector 60                      15
sector 76                      14
sector 55                      14
sector 53                      14
sector 52                      14
sector 1 manesar               14
sector 6                       13
sector 4 phase 2               13
sector 46                      13
sector 9                       13
sector 36a                     13
sector 93                      12
sector 31                      12
sector 38                      12
sector 39                      12
sector 41                      11
sector 3 phase 3 extension     11
sector 9a                      11
sector 13                      10
sector 1a manesar              10
sector 45                       9
sector 95a                      9
manesar                         9
sector 3 phase 2                9
dwarka expressway               8
c block sector 43               8
sector 17                       8
sector 59                       8
sector 89 a                     8
sector 23                       8
sector 2 extension              8
sector 40                       8
sector 10a                      8
sector 8                        8
sector 58                       7
sector 51                       7
sector 36 sohna road road       7
sector 5                        6
sector 21                       6
sector 1                        6
sector 30                       5
sector 23a                      5
sector 80                       5
new sector 2                    5
sector 12a                      4
sector 3a                       4
new                             4
sector 36                       4
patel nagar                     3
sector 73                       3
a block sector 43               3
sector 15                       3
sector 110 a                    3
sector 88b                      3
sector 17b                      3
b block sector 43               3
maruti kunj                     3
sector 17a                      3
sector 27                       3
Name: count, dtype: int64

In [ ]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [ ]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
221,2 BHK Flat in New Gurgaon,flat,Green Court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
711,4 BHK Flat in New Gurgaon,flat,Dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
3336,4 BHK Flat in New Gurgaon,flat,Sare Homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3585,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [ ]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [ ]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
945,2 BHK Flat in New Palam Vihar,flat,Ompee K S Residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2.0,2.0,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1988,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2.0,2.0,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2056,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3.0,2.0,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2923,2 BHK Flat in New Palam Vihar,flat,My Home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2.0,2.0,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3298,2 BHK Flat in New Palam Vihar,flat,My Home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2.0,1.0,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [ ]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [ ]:
df.shape

(3804, 21)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,8 Bedroom House for sale in Sector 12A Gurgaon,house,independent,sector 12,3.50,133079.0,263.0,Plot area 263(24.43 sq.m.)Built Up area: 4800 ...,8.0,8.0,3+,"pooja room,study room,servant room","313, Sector 12A Gurgaon, Gurgaon, Haryana",3.0,South-East,1 to 5 Year Old,"['Hanuman Mandir', 'Dental Health Centre', 'No...",It is situated in well established gated commu...,"['1 Water Purifier', '14 Fan', '1 Exhaust Fan'...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
2,3 BHK Flat in Sector 106 Gurgaon,flat,Paras Dews,sector 106,1.14,6000.0,1900.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3.0,4.0,3,"study room,servant room","Sector 106 Gurgaon, Gurgaon, Haryana",8.0,South,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Located in the popular residential address of ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
3,3 BHK Flat in Sector 53 Gurgaon,flat,Tulip Monsella,sector 53,8.25,28000.0,2946.0,Super Built up area 2940(273.13 sq.m.),3.0,4.0,3,servant room,"Sector 53 Gurgaon, Gurgaon, Haryana",8.0,NaN,Nov 2025,"['Sector 53-54 Metro Station', 'Central Plaza ...",Top of the line property and last property on ...,"['1 Water Purifier', '1 Fridge', '1 Washing Ma...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,sector 66,NaN,NaN,NaN,Plot area 350(292.64 sq.m.),5.0,5.0,3,not available,"Sector 66 Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This property situated in marbella sector 65 g...,"['5 Fan', '1 Exhaust Fan', '6 Geyser', '1 Micr...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Safety4 out of 5', ..."
5,3 BHK Flat in Sector 99A Gurgaon,flat,Pareena Coban Residences,sector 99a,1.40,7010.0,1997.0,Super Built up area 1997(185.53 sq.m.),3.0,5.0,3+,not available,"Sector 99A Gurgaon, Gurgaon, Haryana",6.0,NaN,0 to 1 Year Old,"['Gopal Super Market', 'Little Need Super Mark...",Newly constructed apartment with all amenities,[],"['Swimming Pool', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle3 out of 5..."

In [ ]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [ ]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
300,flat,DLF New Town Heights 24.0 ★,sector 86,1.55,6578.0,2356.0,Super Built up area 2356(218.88 sq.m.)Carpet a...,4.0,4.0,3+,"pooja room,servant room",12.0,North-East,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...","['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1996,flat,Pyramid Elite,sector 86,0.45,7739.0,581.0,Carpet area: 581.41 (54.01 sq.m.),2.0,2.0,1,not available,4.0,NaN,Nov 2023,"['V3S Sapphire Ninety Mall', 'Sector 86 Road',...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'In..."
668,flat,Sare Crescent Parc3.5 ★,sector 92,1.00,4778.0,2093.0,Built Up area: 2093 (194.45 sq.m.),4.0,4.0,3,not available,9.0,NaN,undefined,NaN,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN
3499,flat,The Lions CGHS,sector 56,2.05,9534.0,2150.0,Super Built up area 2150(199.74 sq.m.)Built Up...,4.0,4.0,3,"servant room,others",7.0,West,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...","['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F..."
2234,house,independent,sector 11,NaN,NaN,NaN,Plot area 2700(250.84 sq.m.),6.0,4.0,2,not available,2.0,East,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Stat...","['1 Bed', '1 Wardrobe', '1 Fan', '1 Light', 'N...","['Water Storage', 'Park', 'Waste Disposal']"

In [ ]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [ ]:
df.duplicated().sum()

np.int64(122)

In [ ]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)

In [ ]:
from google.colab import files

files.download('gurgaon_properties_cleaned_v1.csv')